### ISSUE TITLE
Failure on python3.9 as requests-openapi uses python syntax that is not available in python3.9

### ISSUE THREAD

**Issue by maciej-lech** [wy-z/oai-request#11]
Hi

The error is:
```
    ...
    .../lib/python3.9/site-packages/requests_openapi/core.py", line 144, in Client             
            _server: Server | None
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'`.
```

Please pin 0.9.x for python3.9, by adding a proper `python_requires` in `setup.py` or remove that syntax.

Thank you in advance!

Best regards,
Maciej

**Comment by wy-z** [comment]
Hi @maciej-lech ,
Glad to get your feedback, I did miss that point.

I've fixed this (https://github.com/wy-z/requests-openapi/pull/12) and released 1.0.5 (https://github.com/wy-z/requests-openapi/releases/tag/1.0.5).
And it tests fine in a 3.9 environment, so you can try ~

**Comment by wy-z** [comment]
If there are any problems, you can reopen the issue.

**Comment by maciej-lech** [comment]
@wy-z thank you for a very fast response. I will test the new version.
