### ISSUE TITLE
post body

### ISSUE THREAD

**Issue by laktak** [wy-z/oai-request#2]
Thanks for your project - I like the idea of dynamically generating the api instead of having to genereate the code in advance.

I ran into a bug while trying to specify a post body.

I'm trying to pass data as the post body to `requests`:

```
c.addLink(_data={"url": "test", "title": "test"})
```

But there appears to be a bug when you create the kwargs:
```
  File ".../site-packages/requests_openapi/core.py", line 115, in f
    for k in kwargs:
RuntimeError: dictionary keys changed during iteration
```

It would be nice if you could add native support for a request body:

```
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Link"
              }
            }
          }
        },
```

Thanks!

**Comment by wy-z** [comment]
Hi, @laktak. Thank you for the feedback.
May you try `c.addLink(json={"url": "test", "title": "test"})`?

**Comment by laktak** [comment]
Ah, yes, that works. Thank you!

**Comment by wy-z** [comment]
@laktak 
https://github.com/wy-z/requests-openapi/blob/8b8dbe1708863451d1d4bc0ff5ca0c196be639df/requests_openapi/core.py#L120
This line of code is sloppy, I will fix it and enhance unit tests.
Thank you for the feedback again.
